name: build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_name: windows
            artifact_name: hitsz-connect-verge.exe
            arch: x64
            data_separator: ";"
          - os: windows-latest
            os_name: windows
            artifact_name: hitsz-connect-verge.exe
            arch: arm64
            data_separator: ";"
          - os: macos-latest
            os_name: darwin
            artifact_name: hitsz-connect-verge.app
            data_separator: ":"
            arch: x64
          - os: macos-latest
            os_name: darwin
            artifact_name: hitsz-connect-verge.app
            data_separator: ":"
            arch: arm64
          - os: ubuntu-22.04
            os_name: linux
            artifact_name: hitsz-connect-verge
            data_separator: ":"
            arch: x64
          - os: ubuntu-22.04
            os_name: linux
            artifact_name: hitsz-connect-verge
            data_separator: ":"
            arch: arm64
            
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Executable (macOS only)
      if: runner.os == 'macOS'
      run: |
        mv core/zju-connect-${{ matrix.os_name }}-${{ matrix.arch }} core/zju-connect
        pyinstaller --clean --onefile --noconsole --windowed \
          --add-data "assets${{ matrix.data_separator }}assets" \
          --add-data "core/zju-connect:core/zju-connect" \
          --icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.icns \
          -n hitsz-connect-verge main.py

    - name: Zip macOS Executable
      if: runner.os == 'macOS'
      run: |
        cd dist
        zip -r hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}.zip hitsz-connect-verge.app

    - name: Build Executable (Windows only)
      if: runner.os == 'Windows'
      run: |
        Rename-Item -Path core\zju-connect-${{ matrix.os_name }}-${{ matrix.arch }}.exe -NewName zju-connect.exe
        pyinstaller --clean --onefile --noconsole `
          --add-data "assets${{ matrix.data_separator }}assets" `
          --add-data "core/zju-connect.exe:core/zju-connect.exe" `
          --icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.ico `
          -n hitsz-connect-verge main.py

    - name: Build Executable (Linux only)
      if: runner.os == 'Linux'
      run: |
        mv core/zju-connect-${{ matrix.os_name }}-${{ matrix.arch }} core/zju-connect
        pyinstaller --clean --onefile --noconsole \
          --add-data "assets${{ matrix.data_separator }}assets" \
          --add-data "core/zju-connect:core/zju-connect" \
          --icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.png \
          -n hitsz-connect-verge main.py

    - name: Zip Linux Executable
      if: runner.os == 'Linux'
      run: |
        cd dist
        zip -r hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}.zip hitsz-connect-verge

    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          ${{ runner.os == 'Windows' && 'dist/hitsz-connect-verge.exe' || 'dist/*.zip' }}
          

  release:
    permissions: write-all
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: hitsz-connect-verge-*
        merge-multiple: true

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
