name: Build and Release Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: hitsz-connect-verge.exe
            arch: x64
            data_separator: ";"
          - os: macos-latest
            artifact_name: hitsz-connect-verge.app
            data_separator: ":"
            arch: x64
          - os: macos-latest
            artifact_name: hitsz-connect-verge.app
            data_separator: ":"
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Executable(macOS only)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --clean --onefile --noconsole --windowed \
          --add-data "assets${{ matrix.data_separator }}assets" \
          --icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.icns \
          -n hitsz-connect-verge main.py

    - name: Zip macOS Executable
      if: runner.os == 'macOS'
      run: |
        zip -r dist/hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}.zip dist/hitsz-connect-verge.app

    - name: Build Executable(Windows only)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --clean --onefile --noconsole `
          --add-data "assets${{ matrix.data_separator }}assets" `
          --icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.ico `
          -n hitsz-connect-verge main.py

    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          dist/${{ matrix.artifact_name }}
          dist/hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}.zip
          

  release:
    permissions: write-all
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: hitsz-connect-verge-*
        merge-multiple: true

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
