name: Build and Release Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: hitsz-connect-verge.exe
            data_separator: ";"
          - os: macos-latest
            artifact_name: hitsz-connect-verge
            data_separator: ":"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Executable
      shell: bash
      run: |
        pyinstaller --clean --onefile --noconsole \
        --add-data "assets${{ matrix.data_separator }}assets" \
        ${{ runner.os == 'Windows' && '--icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.ico' || '' }} \
        -n hitsz-connect-verge main.py

    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: hitsz-connect-verge-${{ matrix.os }}
        path: dist/${{ matrix.artifact_name }}

  release:
    permissions: write-all
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: hitsz-connect-verge-*
        merge-multiple: true

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
