name: Build and Release Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: hitsz-connect-verge.exe
            data_separator: ";"
          - os: macos-latest
            artifact_name: hitsz-connect-verge
            data_separator: ":"
            arch: x64
          - os: macos-latest
            artifact_name: hitsz-connect-verge
            data_separator: ":"
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install create-dmg (macOS only)
      if: runner.os == 'macOS'
      run: |
        brew install create-dmg

    - name: Build Executable
      shell: bash
      run: |
        if (${{ runner.os }}" == "macOS"); then
          pyinstaller --clean --onefile --noconsole \
          --add-data "assets${{ matrix.data_separator }}assets" \
          --target-architecture ${{ matrix.arch }} \
          -n hitsz-connect-verge main.py
        else
          pyinstaller --clean --onefile --noconsole \
          --add-data "assets${{ matrix.data_separator }}assets" \
          --icon assets/Graphicloads-Colorful-Long-Shadow-Cloud.ico \
          -n hitsz-connect-verge main.py
        fi

    - name: Create DMG (macOS only)
      if: runner.os == 'macOS'
      run: |
        mkdir -p dist/dmg
        cp -r dist/hitsz-connect-verge.app dist/dmg/
        create-dmg \
          --volname "HITSZ Connect Verge" \
          --volicon "assets/Graphicloads-Colorful-Long-Shadow-Cloud.ico" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "hitsz-connect-verge.app" 175 120 \
          --hide-extension "hitsz-connect-verge.app" \
          --app-drop-link 425 120 \
          "dist/HITSZ-Connect-Verge-${{ matrix.arch }}.dmg" \
          "dist/dmg/"

    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: hitsz-connect-verge-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          dist/${{ matrix.artifact_name }}
          dist/*.dmg

  release:
    permissions: write-all
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: hitsz-connect-verge-*
        merge-multiple: true

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
