name: Build and Release Executable

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile --add-data "zju-connect.exe:." main.py

    - name: Archive Executable
      uses: actions/upload-artifact@v3
      with:
        name: hitsz-connect-verge
        path: dist/main*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: hitsz-connect-verge
        path: hitsz-connect-verge

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "hitsz-connect-verge/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
